server:
  port: 8080
　context-path: user_server
#spring.jmx.default-domain: test
spring.jmx.enabled: false
spring:
     datasource:
         name: test
         url: jdbc:mysql://localhost:3306/sharism?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
         username: root
         password: Dys123456.
         # 使用druid数据源
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.jdbc.Driver
         filters: stat
         maxActive: 15
         initialSize: 1
         maxWait: 60000
         minIdle: 1
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: select 'x'
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         poolPreparedStatements: true
         maxOpenPreparedStatements: 20
     kafka:
        bootstrap-servers: 118.25.46.139:9092,118.25.47.192:9092,118.25.48.91:9092
        # 指定kafka 代理地址，可以多个
        producer:
           bootstrap-servers: 118.25.46.139:9092,118.25.47.192:9092,118.25.48.91:9092
           retries: 0
           # 每次批量发送消息的数量
           batch-size: 16384
           buffer-memory: 33554432
           # 指定消息key和消息体的编解码方式
           key-serializer: org.apache.kafka.common.serialization.StringSerializer
           value-serializer: org.apache.kafka.common.serialization.StringSerializer
           #bootstrap-servers: localhost:9092
        consumer:
           # 指定默认消费者group id
           group-id: foo
           # earliest 当分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费。
           # latest 当分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据。
           # none 当该topic下所有分区中存在未提交的offset时，抛出异常。
           auto-offset-reset: earliest
           #指定消息被消费之后自动提交偏移量（即消息的编号，表示消费到了哪个位置，消费者每消费完一条消息就会向kafka服务器汇报自己消消费到的那个消息的编号，以便于下次继续消费）。
           enable-auto-commit: true
           auto-commit-interval: 100
           # 指定消息key和消息体的编解码方式
           key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
           value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sharism.user_server.model


#配置Redis数据库链接
redis:
  host: 127.0.0.1 # Redis服务器地址
  port: 6379      # Redis服务器连接端口
  password:       # Redis服务器连接密码（默认为空）
  timeout: 10000  # 连接超时时间 （毫秒）
  pool:
    max-idle: 20     # 连接池中的最大空闲连接
    min-idle: 1      # 连接池中的最小空闲连接
    max-active: 20   # 连接池最大连接数（使用负值表示没有限制）
    max-wait: 60000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  database: 0        # Redis数据库索引（默认为0）


